"area: Modem":
  - "drivers/modem/**/*"
"area: PWM":
  - "drivers/pwm/**/*"
"area: Watchdog":
  - "drivers/watchdog/**/*"
"area: Sensors":
  - "drivers/sensors/**/*"
"area: ADC":
  - "drivers/adc/**/*"
"area: Counter":
  - "drivers/counter/**/*"
"area: CAN":
  - "include/drivers/can.h"
  - "include/canbus/*/**"
  - "drivers/can/**/*"
  - "subsys/canbus/*/**"
"area: EEPROM":
  - "include/drivers/eeprom.h"
  - "drivers/eeprom/**/*"
"area: Timer":
  - "drivers/timer/**/*"
"area: I2S":
  - "drivers/i2s/**/*"
"area: C Library":
  - "lib/libc/**/*"
"area: Devicetree":
  - "dts/**/*"
  - "!dts/bindings/**/*"
  - "**/*.dts"
  - "**/*.dtsi"
  - "include/devicetree.h"
  - "include/devicetree/*"
  - "doc/guides/dts/**/*"
"area: Devicetree Binding":
  - "include/dt-bindings/**/*"
  - "dts/bindings/**/*"
"area: Devicetree Tooling":
  - "scripts/dts/**/*"
"area: I2C":
  - "drivers/i2c/**/*"
"area: SPI":
  - "drivers/spi/**/*"
"area: Boards":
  - "boards/**/*"
"area: POSIX":
  - "lib/posix/**/*"
"area: native port":
  - "arch/posix/**/*"
  - "include/arch/posix/**/*"
  - "soc/posix/**/*"
  - "**/*native_posix*"
"area: X86":
  - "arch/x86/**/*"
  - "include/arch/x86/**/*"
"area: ARM":
  - "arch/arm/**/*"
  - "include/arch/arm/**/*"
"area: NIOS2":
  - "arch/nios2/**/*"
  - "include/arch/nios2/**/*"
"area: Xtensa":
  - "arch/xtensa/**/*"
  - "include/arch/xtensa/**/*"
"area: RISCv32/64":
  - "arch/risv/**/*"
  - "include/arch/riscv/**/*"
"area: ARC":
  - "arch/arc/**/*"
  - "include/arch/arc/**/*"
"area: Networking":
  - "subsys/net/**/*"
  - "samples/net/**/*"
  - "tests/net/**/*"
  - "include/net/**/*"
  - "include/drivers/ieee802154/**/*"
  - "drivers/ethernet/**/*"
  - "drivers/ieee802154/**/*"
  - "drivers/wifi/**/*"
  - "drivers/ptp_clock/**/*"
  - "drivers/net/**/*"
"area: Logging":
  - "subsys/logging/**/*"
"area: Shell":
  - "subsys/shell/**/*"
"area: Console":
  - "subsys/console/**/*"
"area: Test Framework":
  - "subsys/testsuite/**/*"
"area: Settings":
  - "subsys/settings/**/*"
"area: File System":
  - "subsys/fs/**/*"
"area: Storage":
  - "subsys/storage/**/*"
"area: Bluetooth":
  - "subsys/bluetooth/**/*"
  - "**/*bluetooth*"
"area: Bluetooth Mesh":
  - "subsys/bluetooth/mesh/**/*"
"area: API":
  - "include/**/*"
"area: Samples":
  - "samples/**/*"
"area: Tests":
  - "tests/**/*"
"area: Kernel":
  - "kernel/**/*"
  - "tests/kernel/**/*"
"area: Documentation":
  - "**/*.rst"
  - "**/*.md"
"area: Build System":
  - "cmake/**/*"
  - "CmakeLists.txt"
"area: Kconfig":
  - "scripts/kconfig/**/*"
  - "Kconfig"
  - "Kconfig.zephyr"
"area: Sanitycheck":
  - "scripts/sanitycheck"
  - "scripts/sanity_chk/**/*"
"area: Modules":
  - "west.yml"
  - "modules/**/*"
